<Project>
  <PropertyGroup Label="ThunderPropagatorDependencySuffix">
    <ThunderPropagatorPackageIdConfigurationSuffix>$(PackageIdConfigurationSuffix)</ThunderPropagatorPackageIdConfigurationSuffix>
    <ThunderPropagatorPackageIdConfigurationSuffix Condition="'$(Configuration)' == 'Cluster'"></ThunderPropagatorPackageIdConfigurationSuffix>
  </PropertyGroup>

  <PropertyGroup Label="ThunderPropagatorPackageIds">
    <BuildingBlocksPackageId>ThunderPropagator.BuildingBlocks$(ThunderPropagatorPackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</BuildingBlocksPackageId>
    <BuildingBlocksModulesPackageId>ThunderPropagator.BuildingBlocks.Modules$(ThunderPropagatorPackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</BuildingBlocksModulesPackageId>

    <ThunderPropagatorApplicationPackageId>ThunderPropagator.Application$(ThunderPropagatorPackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</ThunderPropagatorApplicationPackageId>
    <ThunderPropagatorPackageId>ThunderPropagator$(ThunderPropagatorPackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</ThunderPropagatorPackageId>

    <ThunderPropagatorClusterPackageId>ThunderPropagator.Cluster$(PackageIdPlatformSuffix)</ThunderPropagatorClusterPackageId>
    <ThunderPropagatorApplicationClusterPackageId>ThunderPropagator.Application.Cluster$(PackageIdPlatformSuffix)</ThunderPropagatorApplicationClusterPackageId>
  </PropertyGroup>
</Project>
